FROM openjdk:11-jre-slim
EXPOSE 8082
WORKDIR usr/src
ENV MONGO_DATABASE=movies_db
ENV MONGO_URL=mongodb://localhost:27017/movies_db
ADD ./target/MovieServiceApplication-0.0.1.jar /usr/src/MovieServiceApplication-0.0.1.jar
ENTRYPOINT ["java","-jar","MovieServiceApplication-0.0.1.jar"]