FROM openjdk:11-jre-slim
WORKDIR usr/src
EXPOSE 9000
ADD ./target/MuzixAPIGateway-0.0.1-SNAPSHOT.jar /usr/src/MuzixAPIGateway-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","MuzixAPIGateway-0.0.1-SNAPSHOT.jar"]