FROM openjdk:11-jre-slim
EXPOSE 8083
WORKDIR usr/src
ENV MONGO_DATABASE=movies_db
ENV MONGO_URL=mongodb://localhost:27017/movies_db
ADD ./target/SearchServiceApplication-0.0.1.jar /usr/src/SearchServiceApplication-0.0.1.jar
ENTRYPOINT ["java","-jar","SearchServiceApplication-0.0.1.jar"]